

CREATE OR ALTER PROCEDURE addProduct (@PRODUCTID  VARCHAR(255), @PRODUCTNAME VARCHAR(255),@PRICE DECIMAL(10,4),@CATEGORYID VARCHAR(255))
AS
BEGIN

INSERT INTO GETPRODUCTS (PRODUCTID,PRODUCTNAME,PRICE,CATEGORYID) VALUES(@PRODUCTID,@PRODUCTNAME,@PRICE,@CATEGORYID )
END