USE CategoryProducts

CREATE OR ALTER PROCEDURE updateProduct(@PRODUCTID  VARCHAR(255), @PRODUCTNAME VARCHAR(255),@PRICE DECIMAL(10,4),@CATEGORYID VARCHAR(255))
AS
BEGIN

UPDATE GETPRODUCTS SET PRODUCTNAME=@PRODUCTNAME, PRICE=@PRICE,CATEGORYID =@CATEGORYID 
WHERE PRODUCTID =@PRODUCTID 

END