
USE CategoryProducts

CREATE OR ALTER PROCEDURE addCategory
   @CATEGORYID VARCHAR (255), 
   @CATEGORYNAME VARCHAR(255), 
   @CATEGORY VARCHAR(255)
   
AS
BEGIN
    INSERT INTO  CATEGORYPRODUCTS (CATEGORYID ,CATEGORYNAME,CATEGORY )
    VALUES (@CATEGORYID,@CATEGORYNAME,@CATEGORY);
END;
