
CREATE or ALTER PROCEDURE updateCategory(
   @CATEGORYID VARCHAR (255), 
   @CATEGORYNAME VARCHAR(255), 
   @CATEGORY VARCHAR(255))
AS
BEGIN

UPDATE CATEGORYPRODUCTS SET CATEGORYNAME=@CATEGORYNAME,CATEGORY= @CATEGORY WHERE CATEGORYID = @CATEGORYID
END