
USE CategoryProducts

CREATE TABLE GETPRODUCTS
(PRODUCTID VARCHAR(255) PRIMARY KEY,
PRODUCTNAME VARCHAR(50),
PRICE DECIMAL(10,4),
CATEGORYID VARCHAR(255) FOREIGN KEY  REFERENCES PRODUCTS(PRODUCTID) ON DELETE CASCADE NOT NULL
)



